version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compor
      MYSQL_USER: compor_user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      # Nombre del servicio MySQL en el archivo docker-compose
      PMA_HOST: mysql
      # Usuario para conectarse
      PMA_USER: compor_user 
      #Contraseña del usuario
      PMA_PASSWORD: password
    ports:
      # Exponer phpMyAdmin en el puerto 8081
      - "8081:80"
    networks:
      - app-network
volumes:
  db-data:
networks:
  app-network:
    driver: bridge